/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.HospitalAdmin.Hospital;
import Business.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyascr
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem system;
    private  UserAccount user;
    private Hospital resObj;
    private String hosname;
    public DoctorJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount user) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.user = user;
          hosname = user.getEmployee().getName();
        //resObj = system.getHospitalDirectory().findHospital(hosname);
        viewTable();
    }
public void viewTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) doctorDetails.getModel();
        dtm.setRowCount(0);
        
         //System.out.println("Res len "+ system.getDoctorDirectory().getDoctorList());
       String city = user.getEmployee().getCity();
         
        if(system.findNetwork(city).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getOrganizationList()!=null){
        for(Organization org : system.findNetwork(city).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getOrganizationList()) {
           System.out.println(org.getEnterpriseType1().getClass()+" "+ org.getEnterpriseType1().getValue());
                if(org.getEnterpriseType1().getValue().equals("Doctor")){
                    
          
            Object row[] = new Object[3];
            row[0] = org;
            row[1] = org.getName();
            dtm.addRow(row);
        }else{
                    System.out.println("nothing");
                }
        }
        System.out.println("hooos "+hosname);
//        if(resObj!=null && resObj.getDoctorDirectory()!=null){
//        for(Doctor doc : system.getHospitalDirectory().findHospital(hosname).getDoctorDirectory().getDoctorList()) {
//            Object row[] = new Object[3];
//            row[0] = doc;
//            row[1] = doc.getSpecialization();
//            dtm.addRow(row);
//        }
//    }}
}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorDetails = new javax.swing.JTable();
        createNewDoctor = new javax.swing.JButton();
        updateDoctor = new javax.swing.JButton();
        deleteDoctor = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Customer Dashboard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 21, 214, 59));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 51, -1, -1));

        doctorDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor name", "Doctor Specialization"
            }
        ));
        jScrollPane1.setViewportView(doctorDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 125, 580, 119));

        createNewDoctor.setText("Create New Doctor");
        createNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewDoctorActionPerformed(evt);
            }
        });
        add(createNewDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 320, -1, -1));

        updateDoctor.setText("Update Doctor Details");
        updateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorActionPerformed(evt);
            }
        });
        add(updateDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 320, -1, -1));

        deleteDoctor.setText("Delete Doctor");
        deleteDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoctorActionPerformed(evt);
            }
        });
        add(deleteDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

//        Component[] comps = this.userProcessContainer.getComponents();
//        for(Component comp : comps){
//            if(comp instanceof SystemAdminWorkAreaJPanel){
//                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
//                systemAdminWorkAreaJPanel.populateTree();
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewDoctorActionPerformed
        // TODO add your handling code here:

        AddDoctorJpanel createDoctorJPanel = new AddDoctorJpanel(userProcessContainer, system,user);
        userProcessContainer.add("CreateDoctor", createDoctorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createNewDoctorActionPerformed

    private void updateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoctorActionPerformed
        // TODO add your handling code here:
//        int selectedRow = doctorDetails.getSelectedRow();
//        if(selectedRow < 0) {
//            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        Customer customer = (Customer)doctorDetails.getValueAt(selectedRow,0);
//        CustomerDetailsUpdateJPanel customerDetailsUpdateJPanel = new CustomerDetailsUpdateJPanel(userProcessContainer, system, customer);
//        userProcessContainer.add("Update Customer", customerDetailsUpdateJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

    }//GEN-LAST:event_updateDoctorActionPerformed

    private void deleteDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDoctorActionPerformed
        // TODO add your handling code here:

        int selectedRow = doctorDetails.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Doctor doc = (Doctor)doctorDetails.getValueAt(selectedRow,0);
        //system.getDoctorDirectory().deleteDoctor(doc);
        viewTable();
    }//GEN-LAST:event_deleteDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewDoctor;
    private javax.swing.JButton deleteDoctor;
    private javax.swing.JTable doctorDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateDoctor;
    // End of variables declaration//GEN-END:variables
}
